//
// Created by maxxie on 16-7-30.
//

#ifndef SHARPVPN_CHINADNS_H
#define SHARPVPN_CHINADNS_H

#include <string>
#include <thread>
#include <glog/logging.h>
#include <iostream>
#include <fstream>
#ifndef TARGET_WIN32
#include "chinadns.h"
extern "C" int chinadns(const char *chnroute, const char *port, const char *addr, int *running);
#endif // !TARGET_WIN32

class Chinadns{
private:
    std::string host;
    std::string route_file;
    int port;
    int running = 0;
    std::string return_s;
#ifdef TARGET_WIN32
	PROCESS_INFORMATION pi;
#endif
public:
    Chinadns(std::string __host, int __port, std::string __route_file) {
        host = __host;
        route_file = __route_file;
        port = __port;
    }
	Chinadns() {}
#ifdef TARGET_WIN32
	int start() {
		STARTUPINFO si;
		ZeroMemory(&si, sizeof(si));
		ZeroMemory(&pi, sizeof(pi));
		si.dwFlags = STARTF_USESHOWWINDOW;
		si.wShowWindow = SW_HIDE;
		if (CreateProcess(L"dnsrelay.exe", NULL, NULL, NULL,
			false, NULL, NULL, NULL, &si, &pi) == 0) {
			running = 0;
			return -1;
		}
		running = 1;
		return 0;
	}
	int stop() {
		if (running)
			TerminateProcess(pi.hProcess, 300);
		return 0;
	}
#else
    int start() {
        running = 1;
        std::string dns_info = "# Generated by SharpVPN\n"\
                                    "# do not change this file\n"\
                                    "# will be recovered when the program stop\n" \
                                    "nameserver 127.0.0.1\n";
        std::stringstream ss;
        std::ifstream ifs("/etc/resolv.conf");
        if (!ifs) {
            LOG(ERROR) << "can not open /etc/resolv.conf r, chinadns stop";
            return -1;
        }
        ss << ifs.rdbuf();
        return_s = ss.str();
        ifs.close();

        std::ofstream ofs("/etc/resolv.conf");
        if (!ofs) {
            LOG(ERROR) << "can not open /etc/resolve.conf w, chinadns stop";
            return -1;
        }
        ofs << dns_info;
        ofs.close();

        std::thread([this](){
            char port_char[100];
            snprintf(port_char, 20, "%d", port);
            LOG(INFO) << "starting chinadns";
            chinadns(route_file.c_str(), port_char, host.c_str(), &running);
            LOG(INFO) << "chinadns exit";
            return;
        }).detach();
        return 0;
    }
    int stop() {
        if (!running)
            return 0;
        std::ofstream ofs("/etc/resolv.conf");
        running = 0;
        if (!ofs) {
            LOG(ERROR) << "can not open /etc/resolv.conf, chinadns stop";
            return -1;
        }
        ofs << return_s;
        ofs.close();
        return 0;
    }
#endif
};


#endif //SHARPVPN_CHINADNS_H
